import './globals.css';
import { Inter } from 'next/font/google';
import LoginButton from './LoginButton';
import { getServerSession } from 'next-auth';
import LogoutButton from './LogoutButton';
import { authOptions } from '../pages/api/auth/[...nextauth]';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* <button onClick={() => {}}>로그인</button> */}
        {/* 여기엔 로그인 버튼을 둘 수 없는게 onCLick 이 필요한데, 이 컴포넌트는 서버컴포넌트이기때문 */}
        {session ? <LogoutButton /> : <LoginButton />}
        {children}
      </body>
    </html>
  );
}
